theme: minima
title: PIPA 2025
description: Partially ionized plasmas in astrophysics 
logo: /assets/logo.jpg
header_pages:
  logo_width: 1024px
  logo_height: 635px
header_pages:
  - index.md
  - venue.md
  - registration.md
  - accommodation.md
  - program.md
  - ocom.md
  - social.md
  - travel.md
  - contact.md


