theme: minima  # Replace 'minima' with any supported Jekyll theme
title: PIPA 2025
description: Partially ionized plasmas in astrophysics 


minima:
  skin: auto
  social_links: # (Keep your social links if needed)
