theme: jekyll-theme-minimal  # Replace 'minima' with any supported Jekyll theme
title: PIPA 2025
description: Partially ionized plasmas in astrophysics 
logo: /assets/logo.jpg
header_pages:
  logo_width: 60px
  logo_height: 60px

jekyll-theme-minimal:
  skin: dark
  social_links: # (Keep your social links if needed)
  plugins:
  - jekyll-feed
